export const textLib = {
       hello: {
         info_data: 'приветствие',
         ru: 'Привет',
         en: 'Hello',
         es: 'Hola',
         fr: 'Bonjour',
         pt: 'Olá',
         de: 'Hallo',
         zh: '你好',
         it: 'Ciao',
         ja: 'こんにちは',
         ko: '안녕하세요',
         ar: 'مرحبا',
         hi: 'नमस्ते',
         he: 'שָׁלוֹם',
         tr: 'Merhaba',
         vi: 'Xin chào',
         nl: 'Hallo',
         pl: 'Cześć',
         id: 'Halo',
         sv: 'Hej',
         cs: 'Ahoj',
         uk: 'Привіт',
         hu: 'Szervusz',
         th: 'สวัสดี',
         el: 'Γειά',
         da: 'Hej',
         fi: 'Hei',
         ro: 'Salut',
         sk: 'Ahoj',
         be: 'Прывітанне'
       },
       welcom: {
         info_data: 'добро пожаловать',
         ru: 'Добро пожаловать',
         en: 'Welcome',
         es: 'Bienvenido.',
         fr: 'Bienvenue',
         pt: 'Bem-vindo',
         de: 'Herzlich Willkommen',
         zh: '欢迎',
         it: 'Benvenuto',
         ja: 'ようこそ',
         ko: '환영합니다',
         ar: 'مرحبا',
         hi: 'स्वागत है',
         he: 'ברוך הבא',
         tr: 'Hoş geldiniz.',
         vi: 'Chào mừng',
         nl: 'Welkom',
         pl: 'Witaj',
         id: 'Selamat datang',
         sv: 'Välkommen',
         cs: 'Vítejte',
         uk: 'Ласкаво просимо',
         hu: 'Üdvözöljük',
         th: 'ยินดีต้อนรับ',
         el: 'Καλώς ήρθατε',
         da: 'Velkommen',
         fi: 'Tervetuloa',
         ro: 'Bun venit',
         sk: 'Vitajte',
         be: 'Ласкава просімо'
       },
       createservice: {
         info_data: 'создать сервис',
         ru: 'Создать сервис',
         en: 'Create a service',
         es: 'Crear servicio',
         fr: 'Créer un service',
         pt: 'Criar um serviço',
         de: 'Dienst erstellen',
         zh: '创建服务',
         it: 'Creare un servizio',
         ja: 'サービスを作成する',
         ko: '서비스 생성하기',
         ar: 'إنشاء خدمة',
         hi: 'सेवा बनाएं',
         he: 'ליצור שירות',
         tr: 'HİZMET OLUŞTURUŞTURUŞTUR.',
         vi: 'Tạo dịch vụ',
         nl: 'Maak een service',
         pl: 'Utwórz usługę',
         id: 'Membuat Layanan',
         sv: 'Skapa tjänst',
         cs: 'Vytvořit službu',
         uk: 'Створити сервіс',
         hu: 'Szolgáltatás létrehozása',
         th: 'สร้างบริการ',
         el: 'Δημιουργία Υπηρεσίας',
         da: 'Opret en service',
         fi: 'Luoda palvelu',
         ro: 'Creare serviciul',
         sk: 'Vytvoriť službu',
         be: 'Стварыць сервіс'
       },
       DoNotHaveAServiceYet: {
         info_data: 'еще нет сервиса',
         ru: 'Еще нет сервиса?',
         en: 'No service yet?',
         es: '¿Todavía no hay servicio?',
         fr: 'Pas de service encore?',
         pt: 'AINDA NÃO HÁ SERVIÇO?',
         de: 'Noch keinen Service?',
         zh: '还没有服务？',
         it: 'Ancora nessun servizio?',
         ja: 'まだサービスはありませんか？',
         ko: '서비스가 아직 안 준비되었나요?',
         ar: 'لا يوجد خدمة؟',
         hi: 'क्या सेवा अभी तक उपलब्ध नहीं है?',
         he: 'עוד אין שירות?',
         tr: 'HİZMET HENÜZ YOK MU?',
         vi: 'Chưa có dịch vụ?',
         nl: 'Nog geen service?',
         pl: 'NIE MA JESZCZE USŁUGI?',
         id: 'Belum ada layanan?',
         sv: 'Har du inte service ännu?',
         cs: 'Ještě žádná služba?',
         uk: 'Ще немає сервісу?',
         hu: 'Nincs szolgáltatás?',
         th: 'ยังไม่มีบริการ?',
         el: 'Υπάρχει υπηρεσία;',
         da: 'Er der stadig ingen service?',
         fi: 'Eikö palvelua vielä ole?',
         ro: 'Nu este încă serviciu?',
         sk: 'Ešte nie je servis?',
         be: 'Яшчэ няма сэрвiсу?'
       },
       GetPassword: {
         info_data: 'получить пароль',
         ru: 'Получить пароль',
         en: 'Get Password',
         es: 'OBTENER CONTRASEÑA',
         fr: 'Obtenir le mot de passe',
         pt: 'Obter senha',
         de: 'Passwort erhalten',
         zh: '获取密码',
         it: 'Ottenere la password',
         ja: 'パスワード取得',
         ko: '비밀번호 받기',
         ar: 'احصل على كلمة المرور',
         hi: 'पासवर्ड प्राप्त करें',
         he: 'קבל סיסמה',
         tr: 'Şifre Al',
         vi: 'NHẬN MẬT KHẨU',
         nl: 'Wachtwoord ontvangen',
         pl: 'Otrzymać hasło',
         id: 'Dapatkan Kata Sandi',
         sv: 'Få lösenord',
         cs: 'Získat heslo',
         uk: 'Отримати пароль',
         hu: 'Jelszó lekérése',
         th: 'รับรหัสผ่าน',
         el: 'ΛΗΨΗ ΚΩΔΙΚΟΥ',
         da: 'Få adgangskode',
         fi: 'Saada salasana',
         ro: 'Obțineți Parola',
         sk: 'Získať heslo',
         be: 'Атрымаць пароль'
       },
       errorInputEmail: {
         info_data: 'некоректный',
         ru: 'Некорректный',
         en: 'Incorrect',
         es: 'Incorrect',
         fr: 'Incorrect',
         pt: 'Incorreto',
         de: 'Falsch',
         zh: '错误的',
         it: 'Errato',
         ja: '不正確',
         ko: '잘못된',
         ar: 'غير صحيح',
         hi: 'गलत',
         he: 'לא נכון',
         tr: 'HATALI',
         vi: 'Sai',
         nl: 'Onjuist',
         pl: 'Nieprawidłowy',
         id: 'Salah',
         sv: 'Felaktig',
         cs: 'Nesprávný',
         uk: 'Некоректний',
         hu: 'Hibás',
         th: 'ไม่ถูกต้อง',
         el: 'Λάθος',
         da: 'Forkert',
         fi: 'Epäkorrekti',
         ro: 'Incorect',
         sk: 'Nesprávny',
         be: 'Няправільны'
       },
       emailToEmail: {
         info_data: 'пароль отправлен на почту',
         ru: 'Пароль выслан на вашу почту',
         en: 'Password has been sent to your email.',
         es: 'Contraseña enviada a su correo electrónico.',
         fr: 'Le mot de passe a été envoyé sur votre messagerie',
         pt: 'Senha enviada para o seu e-mail.',
         de: 'Passwort wurde an Ihre E-Mail gesendet.',
         zh: '密码已发送到您的邮箱。',
         it: 'La password è stata inviata alla tua email.',
         ja: 'パスワードがあなたのメールアドレスに送信されました。',
         ko: '비밀번호가 이메일로 발송되었습니다.',
         ar: 'تم إرسال كلمة المرور إلى بريدك الإلكتروني.',
         hi: 'आपके ईमेल पर पासवर्ड भेज दिया गया है।',
         he: 'הסיסמה נשלחה לכתובת האימייל שלך',
         tr: '"PAROLA E-POSTANIZA GÖNDERİLDİ"',
         vi: 'MẬT KHẨU ĐÃ ĐƯỢC GỬI QUA EMAIL CỦA BẠN',
         nl: 'WACHTWOORD IS VERZONDEN NAAR UW E-MAIL.',
         pl: 'Hasło zostało wysłane na Twój adres e-mail.',
         id: 'PASSWORD TELAH DIKIRIM KE SUREL ANDA',
         sv: 'Lösenordet skickades till din e-post.',
         cs: 'HESLO BYLO ZASLÁNO NA VÁŠ EMAIL',
         uk: 'Пароль відправлено на вашу пошту.',
         hu: 'Jelszó elküldve az email címére',
         th: 'รหัสผ่านถูกส่งไปยังอีเมลของคุณ',
         el: 'Ο ΚΩΔΙΚΟΣ ΣΑΣ ΕΧΕΙ ΑΠΕΣΤΑΛΕΙ ΣΤΟ ΗΛΕΚΤΡΟΝΙΚΟ ΣΑΣ ΤΑΧΥΔΡΟΜΕΙΟ.',
         da: 'Adgangskoden er blevet sendt til din e-mail.',
         fi: 'SALASANA ON LÄHETETTY SÄHKÖPOSTIISI',
         ro: 'Parola a fost trimisă pe adresa dvs. de email.',
         sk: 'Heslo bolo zaslané na váš e-mail.',
         be: 'Пароль выслан на вашу пошту.'
       },
       back: {
         info_data: 'назад',
         ru: 'Назад',
         en: 'Back',
         es: 'Volver',
         fr: 'Retour',
         pt: 'Voltar',
         de: 'Zurück',
         zh: '返回',
         it: 'Indietro',
         ja: '戻る',
         ko: '뒤로',
         ar: 'العودة',
         hi: 'वापस',
         he: 'אחורה',
         tr: 'Geri',
         vi: 'Trở lại',
         nl: 'Terug',
         pl: 'Wstecz',
         id: 'Kembali',
         sv: 'Tillbaka',
         cs: 'Zpět',
         uk: 'Повернутися',
         hu: 'Vissza',
         th: 'กลับ',
         el: 'Πίσω',
         da: 'Tilbage',
         fi: 'Takaisin',
         ro: 'Înapoi',
         sk: 'Späť',
         be: 'Вярненне'
       },
       enter: {
         info_data: 'вход',
         ru: 'Вход',
         en: 'Entrance',
         es: 'Entrada',
         fr: 'Entrée',
         pt: 'Entrada',
         de: 'Eingang',
         zh: '入口',
         it: 'Entrata',
         ja: '入口',
         ko: '입구',
         ar: 'مدخل',
         hi: 'प्रवेश',
         he: 'כניסה',
         tr: 'Giriş',
         vi: 'Nhập khẩu',
         nl: 'Ingang',
         pl: 'Wejście',
         id: 'Masuk',
         sv: 'Ingång',
         cs: 'Vchod',
         uk: 'Вхід',
         hu: 'Belépés',
         th: 'เข้าสู่ระบบ',
         el: 'ΕΊΣΟΔΟΣ',
         da: 'Indgang',
         fi: 'Sisäänkäynti',
         ro: 'Intrare',
         sk: 'Vstup',
         be: 'Уваход'
       },
       services: {
         info_data: 'сервисы',
         ru: 'Сервисы',
         en: 'Services',
         es: 'Servicios',
         fr: 'Services',
         pt: 'Serviços',
         de: 'Dienstleistungen',
         zh: '服务',
         it: 'Servizi',
         ja: 'サービス',
         ko: '서비스',
         ar: 'الخدمات',
         hi: 'सेवाएँ',
         he: 'שירותי',
         tr: 'Hizmetler',
         vi: 'DỊCH VỤ',
         nl: 'Diensten',
         pl: 'Usługi',
         id: 'Layanan',
         sv: 'Tjänster',
         cs: 'Služby.',
         uk: 'Послуги',
         hu: 'Szolgáltatások',
         th: 'บริการ',
         el: 'ΥΠΗΡΕΣΙΕΣ',
         da: 'Tjenester',
         fi: 'Palvelut',
         ro: 'Servicii',
         sk: 'Služby',
         be: 'Паслугі'
       },
       CampSettings: {
         info_data: 'настройки сервиса',
         ru: 'Настройки сервиса',
         en: 'Service Settings',
         es: 'Configuración del servicio',
         fr: 'Paramètres du service',
         pt: 'Configurações do serviço',
         de: 'Diensteinstellungen',
         zh: '服务设置',
         it: 'Impostazioni del servizio',
         ja: 'サービスの設定',
         ko: '서비스 설정',
         ar: 'إعدادات الخدمة',
         hi: 'सेवा सेटिंग्स',
         he: 'הגדרות שירות',
         tr: 'SERVİS AYARLARI',
         vi: 'Cài đặt dịch vụ',
         nl: 'Service-instellingen',
         pl: 'Ustawienia usługi',
         id: 'Pengaturan Layanan',
         sv: 'Tjänstinställningar',
         cs: 'NASTAVENÍ SLUŽBY',
         uk: 'Налаштування сервісу',
         hu: 'Szolgáltatás beállításai',
         th: 'การตั้งค่าบริการ',
         el: 'ΡΥΘΜΊΣΕΙΣ ΥΠΗΡΕΣΊΑΣ',
         da: 'Serviceindstillinger',
         fi: 'Palvelun asetukset',
         ro: 'Setări serviciu',
         sk: 'Nastavenia služby',
         be: 'Налады сэрвісу'
       },
       workers: {
         info_data: 'настройки сервиса',
         ru: 'Сотрудники',
         en: 'Employees',
         es: 'Empleados',
         fr: 'Employés',
         pt: 'Funcionários',
         de: 'Mitarbeiter.',
         zh: '员工',
         it: 'Dipendenti',
         ja: '社員',
         ko: '직원',
         ar: 'موظفون',
         hi: 'कर्मचारी',
         he: 'עובדים',
         tr: 'ÇALIŞANLAR',
         vi: 'Nhân viên',
         nl: 'Medewerkers',
         pl: 'Pracownicy',
         id: 'Karyawan',
         sv: 'Anställda',
         cs: 'Zaměstnanci',
         uk: 'Працівники',
         hu: 'Munkatársak.',
         th: 'พนักงาน',
         el: 'Υπάλληλοι',
         da: 'Medarbejdere',
         fi: 'Työntekijät',
         ro: 'Angajații',
         sk: 'Zamestnanci',
         be: 'Працоўнікі'
       },
       youDontHaveOrders: {
         info_data: 'нет заказов',
         ru: 'Нет заказов',
         en: 'No orders',
         es: 'Sin Pedidos',
         fr: 'Pas de commandes',
         pt: 'NÃO HÁ PEDIDOS.',
         de: 'Keine Bestellungen',
         zh: '没有订单',
         it: 'Nessun ordine',
         ja: '注文なし',
         ko: '주문없음',
         ar: 'لا توجد طلبات',
         hi: 'कोई आदेश नहीं',
         he: 'אין הזמנות',
         tr: 'SİPARİŞ YOK',
         vi: 'Không có đơn hàng',
         nl: 'Geen Bestellingen',
         pl: 'Brak zamówień',
         id: 'Tidak Ada Pesanan',
         sv: 'Inga beställningar',
         cs: 'Žádné objednávky',
         uk: 'Немає замовлень.',
         hu: 'Nincs rendelés',
         th: 'ไม่มีคำสั่ง',
         el: 'ΚΑΜΙΑ ΠΑΡΑΓΓΕΛΙΑ',
         da: 'Ingen ordrer',
         fi: 'EI TILAUKSIA',
         ro: 'Fără comenzi',
         sk: 'Žiadne objednávky',
         be: 'Няма замоваў'
       },
       settingsMainTable: {
         info_data: 'настройка главного экрана',
         ru: 'Настройка главного экрана',
         en: 'Setting up the main screen',
         es: 'Configuración de la pantalla principal',
         fr: "Réglages de l'écran principal",
         pt: 'Configuração da tela inicial',
         de: 'Hauptbildschirm-Einstellungen',
         zh: '设置主屏幕',
         it: 'Impostazione schermo principale',
         ja: 'メイン画面の設定',
         ko: '화면 설정',
         ar: 'ضبط الشاشة الرئيسية',
         hi: 'मुख्य स्क्रीन को व्यवस्थित करें',
         he: 'הגדרת מסך הבית',
         tr: 'Ana Ekran Ayarları',
         vi: 'Cài đặt Màn hình chính',
         nl: 'Instelling startscherm',
         pl: 'Ustawienia głównego ekranu',
         id: 'Pengaturan Layar Utama',
         sv: 'Inställning av startsidan',
         cs: 'Nastavení hlavní obrazovky',
         uk: 'Налаштування головного екрану',
         hu: 'Főképernyő beállítása',
         th: 'การตั้งค่าหน้าจอหลัก',
         el: 'Ρύθμιση κύριας οθόνης',
         da: 'Opsætning af startskærmen',
         fi: 'Päänäytön asetukset',
         ro: 'Setarea ecranului principal',
         sk: 'Nastavenie hlavného displeja',
         be: 'Настройка галоўнага экрана'
       },
       UserSettings: {
         info_data: 'настройка пользователя',
         ru: 'Настройка пользователя',
         en: 'User Configuration',
         es: 'Configuración de usuario',
         fr: "Configuration de l'utilisateur",
         pt: 'Configuração do usuário',
         de: 'Benutzereinstellungen',
         zh: '用户设置',
         it: 'Configurazione utente',
         ja: 'ユーザー設定',
         ko: '사용자 설정',
         ar: 'ضبط المستخدم',
         hi: 'उपयोगकर्ता सेटिंग्स',
         he: 'הגדרות משתמש',
         tr: 'KULLANICI AYARLARI',
         vi: 'Cấu hình Người dùng',
         nl: 'Gebruikersinstellingen',
         pl: 'Konfiguracja użytkownika',
         id: 'Penyesuaian Pengguna',
         sv: 'Användarinställning',
         cs: 'Nastavení uživatele',
         uk: 'Налаштування користувача',
         hu: 'Felhasználói beállítások',
         th: 'การตั้งค่าผู้ใช้',
         el: 'Ρύθμιση χρήστη',
         da: 'Brugerindstilling',
         fi: 'Käyttäjän asetukset',
         ro: 'Setarea utilizatorului',
         sk: 'Nastavenie používateľa.',
         be: 'Настройка карыстальніка'
       }
     }